### PR TITLE
Identify dashboard view emanating from the app

### PR DESCRIPTION
**Pull request by Andrewsopoku**
**Issue**

- Link: https://github.com/NebraLtd/maker-starter-app/issues/176
- Summary:Identify dashboard page view emanating from the app

**How**

**Screenshots**
abele

asem

**References**

**Checklist**

- [ ] Tests added
- [ ] Cleaned up commit history (rebase!)
- [ ] Documentation added
- [ ] Thought about variable and method names

### CODE REVIEW

**Review by marvinmarnold — COMMENTED** [review]
Did you only visit the homepage and device list page when testing this? Could you also visit the device details page to double check?

image

Also, any clue why the page names are not using the new format? CC: @metawake

**Comment by Andrewsopoku** [comment]
@marvinmarnold https://github.com/NebraLtd/hm-dashboard/pull/1235 hasn't been merged so it appears the other pages are not getting logged.
But since the 2 pages works, the other pages will work when they are correctly logged on the dashboard

**Comment by Andrewsopoku** [comment]
sharingagreement
device
contact

**Comment by marvinmarnold** [comment]
@Andrewsopoku #1235 is merged now but I still only see two pages.

image

**Comment by Andrewsopoku** [comment]
@marvinmarnold your query is against production whereas is #1235 is merge to staging

**Review by marvinmarnold — APPROVED** [review]
Good catch

image

**Pull request merged**
