### PR TITLE
Establish manual build process for Android

### PR DESCRIPTION
**Pull request by posterzh**
**Issue**

- Link: https://github.com/nebraltd/maker-starter-app/issues/19
- Summary: 
For each of the three stages build, sign, and publish, include documentation for:

List of necessary assets that need to be supplied: images, text files, etc
Provide code snippets or link to detailed instructions
Decisions taken: eg key params, build tool, etc

**How**
1. Rename React Native App Name using using [React Native Rename](https://github.com/junedomingo/react-native-rename).
```
npx react-native-rename "Nebra Helium App"
```

2. Change splash screen
(shared assets)
• https://github.com/NebraLtd/maker-starter-app/blob/2712ee44e09a2b9637ae80e18015f59186dc46d2/src/assets/images/SplashScreen.png
• https://github.com/NebraLtd/maker-starter-app/blob/2712ee44e09a2b9637ae80e18015f59186dc46d2/src/assets/images/SplashScreen%402x.png
• https://github.com/NebraLtd/maker-starter-app/blob/2712ee44e09a2b9637ae80e18015f59186dc46d2/src/assets/images/SplashScreen%403x.png
(android)
• https://github.com/NebraLtd/maker-starter-app/blob/2712ee44e09a2b9637ae80e18015f59186dc46d2/android/app/src/main/res/drawable/splashscreen_image.png
• https://github.com/NebraLtd/maker-starter-app/tree/2712ee44e09a2b9637ae80e18015f59186dc46d2/android/app/src/main/res/drawable-hdpi
• https://github.com/NebraLtd/maker-starter-app/tree/2712ee44e09a2b9637ae80e18015f59186dc46d2/android/app/src/main/res/drawable-mdpi
• https://github.com/NebraLtd/maker-starter-app/tree/2712ee44e09a2b9637ae80e18015f59186dc46d2/android/app/src/main/res/drawable-xhdpi
• https://github.com/NebraLtd/maker-starter-app/tree/2712ee44e09a2b9637ae80e18015f59186dc46d2/android/app/src/main/res/drawable-xxhdpi
• https://github.com/NebraLtd/maker-starter-app/tree/2712ee44e09a2b9637ae80e18015f59186dc46d2/android/app/src/main/res/drawable-xxxhdpi
(ios)
• https://github.com/NebraLtd/maker-starter-app/blob/2712ee44e09a2b9637ae80e18015f59186dc46d2/ios/MakerApp/Images.xcassets/SplashScreen.imageset/SplashScreen.png
• https://github.com/NebraLtd/maker-starter-app/blob/2712ee44e09a2b9637ae80e18015f59186dc46d2/ios/MakerApp/Images.xcassets/SplashScreen.imageset/SplashScreen%402x.png
• https://github.com/NebraLtd/maker-starter-app/blob/2712ee44e09a2b9637ae80e18015f59186dc46d2/ios/MakerApp/Images.xcassets/SplashScreen.imageset/SplashScreen%403x.png

3. Change app icon
(shared asset)
• https://github.com/NebraLtd/maker-starter-app/blob/2712ee44e09a2b9637ae80e18015f59186dc46d2/icon.png
(android)
• https://github.com/NebraLtd/maker-starter-app/blob/2712ee44e09a2b9637ae80e18015f59186dc46d2/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
• https://github.com/NebraLtd/maker-starter-app/blob/2712ee44e09a2b9637ae80e18015f59186dc46d2/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
• https://github.com/NebraLtd/maker-starter-app/blob/2712ee44e09a2b9637ae80e18015f59186dc46d2/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
(96 x 96 png is missing in the assets from appvales, made one by resizing)
• https://github.com/NebraLtd/maker-starter-app/blob/2712ee44e09a2b9637ae80e18015f59186dc46d2/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
• https://github.com/NebraLtd/maker-starter-app/blob/2712ee44e09a2b9637ae80e18015f59186dc46d2/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
(192 x 192 png is missing in the assets from appvales, made one by resizing)
(ios)
• https://github.com/NebraLtd/maker-starter-app/blob/2712ee44e09a2b9637ae80e18015f59186dc46d2/ios/MakerApp/Images.xcassets/AppIcon.appiconset/*.png
(31 files)

4. Change text
- https://github.com/NebraLtd/maker-starter-app/blob/b3e236d5ee58db4032dd7af92c1bfa04ee3b99ac/src/makers/example/antennas.ts#L3
- https://github.com/NebraLtd/maker-starter-app/blob/b3e236d5ee58db4032dd7af92c1bfa04ee3b99ac/src/makers/example/hotspots.ts#L5

5. Change logo svg icon
- https://github.com/NebraLtd/maker-starter-app/blob/ce76e0a5509490caad0f657d80140a70545cf513/src/makers/example/icon.svg

6. Change placeholder svg icon
- https://github.com/NebraLtd/maker-starter-app/blob/ce76e0a5509490caad0f657d80140a70545cf513/src/assets/images/placeholder.svg

7. Customize theme and styles
- https://github.com/NebraLtd/maker-starter-app/blob/121f601572d2ddd51019e89132d3e7cc667d479b/src/theme/theme.ts#L113
- https://github.com/NebraLtd/maker-starter-app/blob/4ff35c192adafcdf5bd2ea90081cb27eedd0f52c/src/components/HeliumActionSheet.tsx#L303
- https://github.com/NebraLtd/maker-starter-app/blob/121f601572d2ddd51019e89132d3e7cc667d479b/src/components/Map.tsx#L276

8. Change onboarding server URL
- https://github.com/NebraLtd/maker-starter-app/blob/4c91377d49fcf1cf85e8a26da21c39c83852fdda/src/App.tsx#L125

9. Change maker ID
- https://github.com/NebraLtd/maker-starter-app/blob/b3e236d5ee58db4032dd7af92c1bfa04ee3b99ac/src/makers/example/index.ts#L7

**Screenshots**

**References**

**Checklist**

- [ ] Tests added
- [ ] Cleaned up commit history (rebase!)
- [ ] Documentation added
- [ ] Thought about variable and method names

### CODE REVIEW

**Comment by posterzh** [comment]
Need to update background color in the Splash Screen(On Android motorola)
image

**Comment by posterzh** [comment]
@Andrewsopoku Good finding. Thank you. :+1:

**Comment by marvinmarnold** [comment]
@posterzh don't you need to rework this a little? I thought you manually copied files in for this work when @Andrewsopoku is saying that those assets can be autogenerated.

**Comment by posterzh** [comment]
@marvinmarnold @Andrewsopoku 
The `maker-starter-app` use "expo-splash-screen".
- https://github.com/NebraLtd/maker-starter-app/blob/56c3e12fb5c77079efbebd342bf220f563f0d500/package.json#L71

In [expo-splash-screen documentation](https://www.npmjs.com/package/expo-splash-screen), it's clear said that we should place image assets in native android/ios project directory.
image

Reasoning: If we don't place the splash images under the native project, there may be some glitch during the initial startup of the app, since before react native engine is not running native mobile app runs so splash screen needs to be implemented in native project.

*Note*: In above description automatic configuration means `yarn run configure-splash-screen [option]` command can help us for automatic generation of images, but it also placing images in the native projects.

**Comment by marvinmarnold** [comment]
> @marvinmarnold @Andrewsopoku The `maker-starter-app` use "expo-splash-screen".

Thanks for the explanation. Let's make the splash screen work its own PR in that case. Is there anything else in this PR that you think we should keep?

**Comment by posterzh** [comment]
@marvinmarnold I am OK to close this PR. This can serve solely for documentation purpose what to do. In regard to merging, it's better to split out.

**Pull request closed without merging**
