### PR TITLE
App name updated to Nebra

### PR DESCRIPTION
**Pull request by Andrewsopoku**
**Issue**

- Link: https://github.com/NebraLtd/maker-starter-app/issues/25
- Summary:
    - Rename your application using [React Native Rename](https://github.com/junedomingo/react-native-rename). You will want to pass in the custom bundle identifier for [Android](https://developer.android.com/studio/build/configure-app-module#set_the_application_id) and also change it manually for [iOS](https://developer.apple.com/documentation/appstoreconnectapi/bundle_ids).

**How**
- Install  react-native-rename package
    ```
  npm install react-native-rename -g
  ```
- Run react-native-rename
   ```
   npx react-native-rename "Nebra" -b com.nebra.helium.app
   ```
- Manually change bundle id in iOS

**Screenshots**

**References**
- [react-native-rename](https://github.com/junedomingo/react-native-rename)

**Checklist**

- [ ] Tests added
- [ ] Cleaned up commit history (rebase!)
- [ ] Documentation added
- [ ] Thought about variable and method names

### CODE REVIEW

**Review by posterzh — APPROVED** [review]

**Comment by marvinmarnold** [comment]
@Andrewsopoku any progress with this?

**Comment by Andrewsopoku** [comment]
@marvinmarnold please review

**Review by marvinmarnold — COMMENTED** [review]
@Andrewsopoku it looks like you are adding blank splash screens as part of the PR?

**Comment by Andrewsopoku** [comment]
@marvinmarnold not aware. Can you point me to it?

**Comment by Andrewsopoku** [comment]
It is not empty. They are the @2x and @3x versions of old splash screen. 
@posterzh please any reason why you didn't generate @2x and @3x versions of the new splash screen?

can i remove the old splashscreen @2x and @3x versions?

**Comment by marvinmarnold** [comment]
> It is not empty. They are the @2x and @3x versions of old splash screen. @posterzh please any reason why you didn't generate @2x and @3x versions of the new splash screen?
> 
> can i remove the old splashscreen @2x and @3x versions?

Ya I meant default splashscreens, not empty. Feel free to merge the PR but we'll need to follow up and fix those splashscreens.

**Pull request merged**
